eboutique/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('maBoutique.urls')),
    re_path(r'^maBoutique/', include('maBoutique.urls'))

]

maBoutique/urls.py
from django.urls import path
from .views import article_list, article_detail, article_delete, home, articleForm

urlpatterns=[
    path('',home),
    path('index.html',home),
    path('article_list',article_list),
    path('article_detail/<id>/',article_detail),
    path('addArticle',articleForm),
    path('<id>/delete/',article_delete),
]

maBoutique/models.py
from django.db import models
from django.contrib.auth.models import User
class Article(models.Model):
    titre = models.CharField(max_length=150)
    description = models.TextField()
    def str (self):
        return self.titre

maBoutique/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .form import ArticleForm
from .models import Article

def home(request):
    return render(request, "index.html")
    #return render(request, "accueil.html")
    #return HttpResponse('<html><body><p>Bienvenue !</P></body></html>')


def article_list(request):
    article = Article.objects.all()
    context = {'article_list': article}
    return render(request, "article_list.html", context)


def article_detail(request, id):
    each_article = Article.objects.get(id=id)
    context = {'article_detail': each_article}
    return render(request, "article_detail.html", context)


def article_delete(request, id):
    each_article = Article.objects.get(id=id)
    each_article.delete()
    return article_list(request)

def articleForm(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST or None)
        if form.is_valid():
            titre = form.cleaned_data['titre']
            description = form.cleaned_data['description']
            form.save()
            return article_list(request)
    else:
        # Si ce n'est pas du POST, c'est probablement une requête GET
        form = ArticleForm()	# Nous créons un formulaire vide
        return render(request, 'form.html', locals() )

templates/about.html
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Spering</title>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="../maBoutique/static/css/bootstrap.css" />

  <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="../maBoutique/static/css/style.css" rel="stylesheet" />
  <!-- responsive style -->
  <link href="../maBoutique/static/css/responsive.css" rel="stylesheet" />
</head>

<body class="sub_page">
  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container">
          <a class="navbar-brand" href="index.html">
            <img src="{% static 'images/logo.png ' %}" alt=""> />
            <span>
              Spering
            </span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  ">
              <li class="nav-item">
                <a class="nav-link" href="index.html">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="about.html"> About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="work.html">Work </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="category.html"> Category </a>
              </li>
            </ul>
            <div class="user_option">
              <a href="">
                <span>
                  Login
                </span>
              </a>
              <form class="form-inline my-2 my-lg-0 ml-0 ml-lg-4 mb-3 mb-lg-0">
                <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit"></button>
              </form>
            </div>
          </div>
          <div>
            <div class="custom_menu-btn ">
              <button>
                <span class=" s-1">

                </span>
                <span class="s-2">

                </span>
                <span class="s-3">

                </span>
              </button>
            </div>
          </div>

        </nav>
      </div>
    </header>
    <!-- end header section -->
  </div>


  <!-- experience section -->

  <section class="experience_section layout_padding-top layout_padding2-bottom">
    <div class="container">
      <div class="row">
        <div class="col-md-5">
          <div class="img-box">
            <img src="{% static 'images/experience-img.jpg ' %}" alt="">
          </div>
        </div>
        <div class="col-md-7">
          <div class="detail-box">
            <div class="heading_container">
              <h2>
                Best Experinced Freelancer Here
              </h2>
            </div>
            <p>
              It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as
            </p>
            <div class="btn-box">
              <a href="" class="btn-1">
                Read More
              </a>
              <a href="" class="btn-2">
                Hire
              </a>
            </div>
          </div>
        </div>

      </div>
    </div>
  </section>

  <!-- end experience section -->


  <!-- about section -->

  <section class="about_section layout_padding-bottom">
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-lg-9 mx-auto">
          <div class="img-box">
            <img src="{% static 'images/about-img.jpg ' %}" alt="">
          </div>
        </div>
      </div>
      <div class="detail-box">
        <h2>
          About Spering Company
        </h2>
        <p>
          There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If youThere are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you
        </p>
        <a href="">
          Read More
        </a>
      </div>
    </div>
  </section>

  <!-- end about section -->

  <!-- info section -->

  <section class="info_section ">
    <div class="info_container layout_padding-top">
      <div class="container">
        <div class="info_top">
          <div class="info_logo">
            <img src="{% static 'images/logo.png ' %}" alt=""> />
            <span>
              Spering
            </span>
          </div>
          <div class="social_box">
            <a href="#">
              <img src="{% static 'images/fb.png ' %}" alt="">
            </a>
            <a href="#">
              <img src="{% static 'images/twitter.png ' %}" alt="">
            </a>
            <a href="#">
              <img src="{% static 'images/linkedin.png ' %}" alt="">
            </a>
            <a href="#">
              <img src="{% static 'images/instagram.png ' %}" alt="">
            </a>
            <a href="#">
              <img src="{% static 'images/youtube.png ' %}" alt="">
            </a>
          </div>
        </div>

        <div class="info_main">
          <div class="row">
            <div class="col-md-3 col-lg-2">
              <div class="info_link-box">
                <h5>
                  Useful Link
                </h5>
                <ul>
                  <li class=" active">
                    <a class="" href="index.html">Home <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="">
                    <a class="" href="about.html">About </a>
                  </li>
                  <li class="">
                    <a class="" href="work.html">Work </a>
                  </li>
                  <li class="">
                    <a class="" href="category.html">Category </a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-md-3 ">
              <h5>
                Offices
              </h5>
              <p>
                Readable content of a page when looking at its layoutreadable content of a page when looking at its layout
              </p>
            </div>

            <div class="col-md-3 col-lg-2 offset-lg-1">
              <h5>
                Information
              </h5>
              <p>
                Readable content of a page when looking at its layoutreadable content of a page when looking at its layout
              </p>
            </div>

            <div class="col-md-3  offset-lg-1">
              <div class="info_form ">
                <h5>
                  Newsletter
                </h5>
                <form action="">
                  <input type="email" placeholder="Email">
                  <button>
                    Subscribe
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-9 col-md-10 mx-auto">
            <div class="info_contact layout_padding2">
              <div class="row">
                <div class="col-md-3">
                  <a href="#" class="link-box">
                    <div class="img-box">
                      <img src="{% static 'images/location.png ' %}" alt="">
                    </div>
                    <div class="detail-box">
                      <h6>
                        Location
                      </h6>
                    </div>
                  </a>
                </div>
                <div class="col-md-4">
                  <a href="#" class="link-box">
                    <div class="img-box">
                      <img src="{% static 'images/mail.png ' %}" alt="">
                    </div>
                    <div class="detail-box">
                      <h6>
                        demo@gmail.com
                      </h6>
                    </div>
                  </a>
                </div>
                <div class="col-md-5">
                  <a href="#" class="link-box">
                    <div class="img-box">
                      <img src="{% static 'images/call.png ' %}" alt="">
                    </div>
                    <div class="detail-box">
                      <h6>
                        Call +01 1234567890
                      </h6>
                    </div>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </section>

  <!-- end info section -->

  <!-- footer section -->
  <footer class="container-fluid footer_section ">
    <div class="container">
      <p>
        &copy; <span id="displayDate"></span> All Rights Reserved By
        <a href="https://html.design/">Free Html Templates</a>
      </p>
    </div>
  </footer>
  <!-- end  footer section -->


  <script src="../maBoutique/static/js/jquery-3.4.1.min.js"></script>
  <script src="../maBoutique/static/js/bootstrap.js"></script>
  <script src="../maBoutique/static/js/custom.js"></script>


</body>
</body>

</html>

templates/accueil.html
<h1>Bienvenue sur ma boutique</h1>
<p>La date actuelle est : {{ current_date }}</p>

   {% load static %}
<img src="{% static '{% static 'imagesabout-img.jpg' %}" alt="My image">
<img src="{% static '{% static 'images/experience-img.jpg' %} ' %}" alt="">

templates/article_detail.html
<h1>Détail article: {{article_detail.titre}} </h1>
{{article_detail.description}}
<br>
<a href="/{{article_detail.id}}/delete/" >Delete this Article</a>

templates/article_list.html
<h1> list articles</h1>
<ol>
    {% for list in article_list %}
        <li> <a href="/article_detail/{{ list.id}}"><b>{{ list.titre }}</b></a>  </li>
    {% endfor %}
</ol>

templates/category.html
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Spering</title>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="../maBoutique/static/css/bootstrap.css" />

  <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="../maBoutique/static/css/style.css" rel="stylesheet" />
  <!-- responsive style -->
  <link href="../maBoutique/static/css/responsive.css" rel="stylesheet" />
</head>

<body class="sub_page">
  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container">
          <a class="navbar-brand" href="index.html">
            <img src="{% static 'images/logo.png ' %}" alt=""> />
            <span>
              Spering
            </span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  ">
              <li class="nav-item ">
                <a class="nav-link" href="index.html">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="about.html"> About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="work.html">Work </a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="category.html"> Category </a>
              </li>
            </ul>
            <div class="user_option">
              <a href="">
                <span>
                  Login
                </span>
              </a>
              <form class="form-inline my-2 my-lg-0 ml-0 ml-lg-4 mb-3 mb-lg-0">
                <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit"></button>
              </form>
            </div>
          </div>
          <div>
            <div class="custom_menu-btn ">
              <button>
                <span class=" s-1">

                </span>
                <span class="s-2">

                </span>
                <span class="s-3">

                </span>
              </button>
            </div>
          </div>

        </nav>
      </div>
    </header>
    <!-- end header section -->
  </div>

  <!-- category section -->

  <section class="category_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2>
          Category
        </h2>
      </div>
      <div class="category_container">
        <div class="box">
          <div class="img-box">
            <img src="{% static 'images/c1.png ' %}" alt="">
          </div>
          <div class="detail-box">
            <h5>
              Design & Arts
            </h5>
          </div>
        </div>
        <div class="box">
          <div class="img-box">
            <img src="{% static 'images/c2.png ' %}" alt="">
          </div>
          <div class="detail-box">
            <h5>
              Web Development
            </h5>
          </div>
        </div>
        <div class="box">
          <div class="img-box">
            <img src="{% static 'images/c3.png ' %}" alt="">
          </div>
          <div class="detail-box">
            <h5>
              SEO Markting
            </h5>
          </div>
        </div>
        <div class="box">
          <div class="img-box">
            <img src="{% static 'images/c4.png ' %}" alt="">
          </div>
          <div class="detail-box">
            <h5>
              Video Edting
            </h5>
          </div>
        </div>
        <div class="box">
          <div class="img-box">
            <img src="{% static 'images/c5.png ' %}" alt="">
          </div>
          <div class="detail-box">
            <h5>
              Logo Design
            </h5>
          </div>
        </div>
        <div class="box">
          <div class="img-box">
            <img src="{% static 'images/c6.png ' %}" alt="">
          </div>
          <div class="detail-box">
            <h5>
              Game Design
            </h5>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- end category section -->

  <!-- info section -->

  <section class="info_section ">
    <div class="info_container layout_padding-top">
      <div class="container">
        <div class="info_top">
          <div class="info_logo">
            <img src="{% static 'images/logo.png ' %}" alt=""> />
            <span>
              Spering
            </span>
          </div>
          <div class="social_box">
            <a href="#">
              <img src="{% static 'images/fb.png ' %}" alt="">
            </a>
            <a href="#">
              <img src="{% static 'images/twitter.png ' %}" alt="">
            </a>
            <a href="#">
              <img src="{% static 'images/linkedin.png ' %}" alt="">
            </a>
            <a href="#">
              <img src="{% static 'images/instagram.png ' %}" alt="">
            </a>
            <a href="#">
              <img src="{% static 'images/youtube.png ' %}" alt="">
            </a>
          </div>
        </div>

        <div class="info_main">
          <div class="row">
            <div class="col-md-3 col-lg-2">
              <div class="info_link-box">
                <h5>
                  Useful Link
                </h5>
                <ul>
                  <li class=" active">
                    <a class="" href="index.html">Home <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="">
                    <a class="" href="about.html">About </a>
                  </li>
                  <li class="">
                    <a class="" href="work.html">Work </a>
                  </li>
                  <li class="">
                    <a class="" href="category.html">Category </a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-md-3 ">
              <h5>
                Offices
              </h5>
              <p>
                Readable content of a page when looking at its layoutreadable content of a page when looking at its layout
              </p>
            </div>

            <div class="col-md-3 col-lg-2 offset-lg-1">
              <h5>
                Information
              </h5>
              <p>
                Readable content of a page when looking at its layoutreadable content of a page when looking at its layout
              </p>
            </div>

            <div class="col-md-3  offset-lg-1">
              <div class="info_form ">
                <h5>
                  Newsletter
                </h5>
                <form action="">
                  <input type="email" placeholder="Email">
                  <button>
                    Subscribe
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-9 col-md-10 mx-auto">
            <div class="info_contact layout_padding2">
              <div class="row">
                <div class="col-md-3">
                  <a href="#" class="link-box">
                    <div class="img-box">
                      <img src="{% static 'images/location.png ' %}" alt="">
                    </div>
                    <div class="detail-box">
                      <h6>
                        Location
                      </h6>
                    </div>
                  </a>
                </div>
                <div class="col-md-4">
                  <a href="#" class="link-box">
                    <div class="img-box">
                      <img src="{% static 'images/mail.png ' %}" alt="">
                    </div>
                    <div class="detail-box">
                      <h6>
                        demo@gmail.com
                      </h6>
                    </div>
                  </a>
                </div>
                <div class="col-md-5">
                  <a href="#" class="link-box">
                    <div class="img-box">
                      <img src="{% static 'images/call.png ' %}" alt="">
                    </div>
                    <div class="detail-box">
                      <h6>
                        Call +01 1234567890
                      </h6>
                    </div>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </section>

  <!-- end info section -->

  <!-- footer section -->
  <footer class="container-fluid footer_section ">
    <div class="container">
      <p>
        &copy; <span id="displayDate"></span> All Rights Reserved By
        <a href="https://html.design/">Free Html Templates</a>
      </p>
    </div>
  </footer>
  <!-- end  footer section -->


  <script src="../maBoutique/static/js/jquery-3.4.1.min.js"></script>
  <script src="../maBoutique/static/js/bootstrap.js"></script>
  <script src="../maBoutique/static/js/custom.js"></script>

</body>
</body>

</html>

templates/form.html
<body>
<form method="POST">
    {% csrf_token %}
    {{ form.as_div }}
    <input type="submit" value="Add Article">
</form>


<input type="hidden" name="csrfmiddlewaretoken"
       value="Ju2hNK4XKLOyrvbYmVmwm2n8rvt8dN4i9SfZVACjXWR3gpgVLCL5mNmAaTX5T1NO">
<div>
    <label for="id_titre">Titre:</label>
    <input type="text" name="titre" maxlength="150" required="" id="id_titre">
</div>

<div>
    <label for="id_description">Description:</label>
    <textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea>
</div>
<input type="submit" value="Add Article">


</body>